apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres17
spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgres
  template:
    metadata:
      labels:
        role: postgres
    spec:
      containers:
        - name: postgres17
          image: postgres:17.7
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: escorpion2020
            - name: POSTGRES_DB
              value: msvc_cursos
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          PersistentVolumeClaim:
            claimName: postgres-pvc 