version: "3.9"

services:

  mysql-microservicio:
    container_name: mysql-microservicio
    image: mysql:8.0.34
    ports:
      - "3307:3306"
    networks:
      - spring
    volumes:
      - data-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always

  postgres-microservicio:
    container_name: postgres-microservicio
    image: postgres:17.7
    ports:
      - "5433:5432"
    networks:
      - spring
    volumes:
      - data-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

  msvc-usuarios:
    container_name: msvc-usuarios
    image: zvalentinoz/usuarios:latest
    environment:
      PORT: 8001
      DB_HOST: mysql-microservicio
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: tino
      DB_PASSWORD: escorpion2020
      CURSOS_URL: msvc-cursos:8002
    ports:
      - "8001:8001"
    networks:
      - spring
    depends_on:
      - mysql-microservicio
	  

  msvc-cursos:
    container_name: msvc-cursos
    image: zvalentinoz/cursos:latest
    environment:
      PORT: 8002
      DB_HOST: postgres-microservicio
      DB_DATABASE: msvc_cursos
      DB_USERNAME: postgres
      DB_PASSWORD: escorpion2020
      USUARIOS_URL: msvc-usuarios:8001
    ports:
      - "8002:8002"
    networks:
      - spring
    depends_on:
      - postgres-microservicio
	  -msvc-usuarios

networks:
  spring:
    driver: bridge

volumes:
  data-mysql:
  data-postgres:
