apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuarios
type: Opaque
data:
  username: cm9vdAo=
  password: ZXNjb3JwaW9uMjAyMA==
  
---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: ZXNjb3JwaW9uMjAyMA==